DELETE FROM ASSINATURA;
DELETE FROM CLIENTE;
DELETE FROM PRODUTO;

INSERT INTO PRODUTO (DESCRICAO) VALUES ('REVISTA CAPRICHO');
INSERT INTO PRODUTO (DESCRICAO) VALUES ('REVISTA VEJA');
INSERT INTO PRODUTO (DESCRICAO) VALUES ('REVISTA EXAME');
INSERT INTO PRODUTO (DESCRICAO) VALUES ('REVISTA PLACAR');
INSERT INTO PRODUTO (DESCRICAO) VALUES ('REVISTA SUPERINTERESSANTE');